// <auto-generated />
using System;
using Biller.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biller.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biller.Domain.Entities.Cfdi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<int>("EstatusPago")
                        .HasColumnType("integer");

                    b.Property<int>("EstatusTimbrado")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmisor")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturaRelacion")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("integer");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer");

                    b.Property<int>("IdReceptor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsoCfdi")
                        .HasColumnType("integer");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ObjetoImpuesto")
                        .HasColumnType("integer");

                    b.Property<decimal>("TipoCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("integer");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmisor");

                    b.HasIndex("IdReceptor");

                    b.ToTable("Cfdis", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.CfdiComplementoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("Equivalencia")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCfdi")
                        .HasColumnType("integer");

                    b.Property<int>("IdFacturaRelacion")
                        .HasColumnType("integer");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("integer");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("ImportePagado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ImportePagadoInsoluto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ImporteSaldoAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("NumOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumParcialidad")
                        .HasColumnType("integer");

                    b.Property<int>("ObjetoImpuesto")
                        .HasColumnType("integer");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TipoCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("IdCfdi");

                    b.ToTable("CfdiComplementosPago", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.CfdiConcepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<int>("IdCfdi")
                        .HasColumnType("integer");

                    b.Property<int>("IdServicio")
                        .HasColumnType("integer");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TrasladoIva")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdCfdi");

                    b.ToTable("CfdiConceptos", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.Emisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Emisores", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monedas", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.MotivoCancelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MotivosCancelacion", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.Receptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DomicilioFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdRegimenFiscal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsoCfdi")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdRegimenFiscal");

                    b.HasIndex("IdUsoCfdi");

                    b.ToTable("Receptores", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.RegimenFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaveSat")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RegimenesFiscales", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.UsoCfdi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveSat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UsosCfdi", (string)null);
                });

            modelBuilder.Entity("Biller.Domain.Entities.Cfdi", b =>
                {
                    b.HasOne("Biller.Domain.Entities.Emisor", "Emisor")
                        .WithMany("Cfdis")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biller.Domain.Entities.Receptor", "Receptor")
                        .WithMany("Cfdis")
                        .HasForeignKey("IdReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("Biller.Domain.Entities.CfdiComplementoPago", b =>
                {
                    b.HasOne("Biller.Domain.Entities.Cfdi", "Cfdi")
                        .WithMany("ComplementosPago")
                        .HasForeignKey("IdCfdi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("Biller.Domain.Entities.CfdiConcepto", b =>
                {
                    b.HasOne("Biller.Domain.Entities.Cfdi", "Cfdi")
                        .WithMany("Conceptos")
                        .HasForeignKey("IdCfdi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("Biller.Domain.Entities.Receptor", b =>
                {
                    b.HasOne("Biller.Domain.Entities.RegimenFiscal", "RegimenFiscal")
                        .WithMany("Receptores")
                        .HasForeignKey("IdRegimenFiscal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biller.Domain.Entities.UsoCfdi", "UsoCfdi")
                        .WithMany("Receptores")
                        .HasForeignKey("IdUsoCfdi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegimenFiscal");

                    b.Navigation("UsoCfdi");
                });

            modelBuilder.Entity("Biller.Domain.Entities.Cfdi", b =>
                {
                    b.Navigation("ComplementosPago");

                    b.Navigation("Conceptos");
                });

            modelBuilder.Entity("Biller.Domain.Entities.Emisor", b =>
                {
                    b.Navigation("Cfdis");
                });

            modelBuilder.Entity("Biller.Domain.Entities.Receptor", b =>
                {
                    b.Navigation("Cfdis");
                });

            modelBuilder.Entity("Biller.Domain.Entities.RegimenFiscal", b =>
                {
                    b.Navigation("Receptores");
                });

            modelBuilder.Entity("Biller.Domain.Entities.UsoCfdi", b =>
                {
                    b.Navigation("Receptores");
                });
#pragma warning restore 612, 618
        }
    }
}
